[theme]

# Primary accent for interactive elements
primaryColor = '#FF4B4B'

# Background color for the main content area
backgroundColor = '#FFFFFF'
#backgroundColor = '#F08080' #alternative


# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F0F2F6'

# Color used for almost all text
textColor = '#262730'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true